language: android
android:
  components:
    - android-27
    - build-tools-27.0.3
    - extra-google-m2repository
    - extra-android-support
    - extra-android-m2repository

script: ./gradlew assemble test check